import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import OpenAI from 'openai';

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(request: Request, { params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = await params;
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    if (!projectId) {
      return NextResponse.json({ error: 'Project ID is required' }, { status: 400 });
    }
    const { idea, logline, treatment, theme } = await request.json();
    if (!idea || !logline || !treatment) {
      return NextResponse.json({ error: 'Idea, logline, and treatment are required' }, { status: 400 });
    }
    // Optionally verify project ownership
    const project = await prisma.project.findUnique({
      where: { id: projectId, userId: session.user.id },
    });
    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }
    // Compose prompt for OpenAI
    const prompt = `Given the following story details, generate two sections:\n\n1. Visual Style: Describe the intended visual aesthetic, color palette, cinematography style, and overall look and feel of the film in 2-3 sentences.\n2. Key Visual Moments: List 3-5 important visual moments, symbols, or cinematic opportunities that should be highlighted in the film.\n\nIdea: ${idea}\nLogline: ${logline}\nTreatment: ${treatment}\n${theme ? `Themes: ${theme}\n` : ''}\nVisual Style:\n`;
    const completion = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 300,
      temperature: 0.7,
    });
    const generatedContent = completion.choices[0]?.message?.content?.trim();
    if (!generatedContent) {
      throw new Error('No content generated by OpenAI.');
    }
    // Parse the response into visualStyle and keyVisualMoments
    const visualStyleMatch = generatedContent.match(/Visual Style:\s*([\s\S]*?)\n\s*Key Visual Moments:/i);
    const keyVisualMomentsMatch = generatedContent.match(/Key Visual Moments:\s*([\s\S]*)/i);
    const visualStyle = visualStyleMatch ? visualStyleMatch[1].trim() : '';
    const keyVisualMoments = keyVisualMomentsMatch ? keyVisualMomentsMatch[1].trim() : '';
    return NextResponse.json({ visualStyle, keyVisualMoments });
  } catch (error) {
    console.error('[API - Generate Visual Elements] Error:', error);
    const errorMessage = error instanceof Error ? error.message : 'An unknown error occurred';
    return NextResponse.json({ error: errorMessage, details: error instanceof Error ? error.stack : null }, { status: 500 });
  }
} 