import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { generateContent } from '@/lib/gemini';

export async function POST(request: Request, { params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = await params;
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    if (!projectId) {
      return NextResponse.json({ error: 'Project ID is required' }, { status: 400 });
    }
    const { idea, logline, treatment } = await request.json();
    
    // At least one of idea, logline, or treatment must be provided
    if (!idea && !logline && !treatment) {
      return NextResponse.json({ error: 'At least one of idea, logline, or treatment is required' }, { status: 400 });
    }
    // Optionally verify project ownership
    const project = await prisma.project.findUnique({
      where: { id: projectId, userId: session.user.id },
    });
    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }
    
    // Build context from available content
    let contextParts: string[] = [];
    if (idea) contextParts.push(`Idea: ${idea}`);
    if (logline) contextParts.push(`Logline: ${logline}`);
    if (treatment) contextParts.push(`Treatment: ${treatment}`);
    const storyContext = contextParts.join('\n');
    
    // Compose prompt for Gemini
    const userPrompt = `Given the following story details, generate a concise list of 2-4 cinematic themes that would be explored in the film. Each theme should be a short phrase or sentence, focusing on universal, emotional, or philosophical ideas (e.g., "The cost of ambition", "Redemption through sacrifice", "The search for identity").\n\n${storyContext}\n\nThemes:`;
    
    const result = await generateContent({
      model: 'flash',
      userPrompt,
      maxTokens: 200,
      temperature: 0.7,
    });
    
    const generatedContent = result.text.trim();
    if (!generatedContent) {
      throw new Error('No content generated by Gemini.');
    }
    return NextResponse.json({ theme: generatedContent });
  } catch (error) {
    console.error('[API - Generate Theme] Error:', error);
    const errorMessage = error instanceof Error ? error.message : 'An unknown error occurred';
    return NextResponse.json({ error: errorMessage, details: error instanceof Error ? error.stack : null }, { status: 500 });
  }
} 